title: layers
description: >-
  inspiration, raw ideas, unfinished dreams, projects I won’t do, 
  unfiltered thoughts, half-formed concepts, untouched potential, 
  things I like, personal matters, nonsense, whatever, and anti-perfectionism.
baseurl: ""
url: "https://icodeweb.github.io/"
author: ibrahim ismail
twitter_username: 6962726168696d
github_username: icodeweb
instagram_username: i.ismail98

theme: minima
plugins:
  - jekyll-feed
